config/routes.rb
Rails.application.routes.draw do

  resources :notifications
  patch '/markAsRead' => 'notifications#markAsRead'
  get '/markAsRead' => 'notifications#index'
  
  get '/signedinuserprofile' => 'users#signedinuserprofile'
  
  post '/showOrganizerEvents' => 'events#showOrganizerEvents'
  get '/showOrganizerEvents' => 'events#showOrganizerEvents'
  
  post '/showEventRating' => 'ratings#showEventRating'
  get '/showEventRating' => 'ratings#showEventRating'

  delete '/deleteWishlistFromEvent' => 'wishlists#deleteWishlistFromEvent'

  delete '/deleteSubscribeFromEvent' => 'subscriptions#deleteSubscribeFromEvent'

  get 'events_imports/new'
  get 'events_imports/create'
  
  devise_for :users
  
  root 'home#index'
  
  get 'search/index' => 'search#index'
  post '/show' => 'search#show'
  
  get 'search/show' => 'search#show'
  get '/home/index' => 'home#index'

  resources :users
  resources :orders
  resources :wishlists
  resources :subscriptions

  resources :events do
    resources :tickets
  end

  resources :ratings
  
  resources :events_imports, only: [:new, :create]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  mount_uploader :picture, PictureUploader

  has_many :tickets
  has_many :ratings

  EVENT_CATEGORY  = ["", "Charity and Causes", "Competition", "Concert", "Conference", "Convention", "Education", "Fair", "Fashion and Beauty", "Film and Entertainment", "Food and Drink", "Health and Wellness", "Home and Lifestyle", "Performing and Visual Arts", "Religion and Spirituality", "Science and Technology", "Seminar", "Singing", "Sports and Fitness", "Travel and Outdoor", "Workshop"]
  EVENT_CITY  = ["", "Antrim", "Armagh", "Carlow", "Cavan", "Clare", "Cork", "Derry", "Donegal", "Down", "Dublin", "Fermanagh", "Galway", "Kerry", "Kildare", "Kilkenny", "Laois", "Leitrim", "Limerick", "Longford", "Louth", "Mayo", "Meath", "Monaghan", "Offaly", "Roscommon", "Sligo", "Tipperary", "Tyrone", "Waterford", "Westmeath", "Wexford", "Wicklow"]
  EVENT_COUNTY  = ["", "Antrim", "Armagh", "Carlow", "Cavan", "Clare", "Cork", "Derry", "Donegal", "Down", "Dublin", "Fermanagh", "Galway", "Kerry", "Kildare", "Kilkenny", "Laois", "Leitrim", "Limerick", "Longford", "Louth", "Mayo", "Meath", "Monaghan", "Offaly", "Roscommon", "Sligo", "Tipperary", "Tyrone", "Waterford", "Westmeath", "Wexford", "Wicklow"]
  EVENT_COUNTRY  = ["Republic of Ireland"]

  validates_format_of :title, :category, :description, :organizer_name, :venue, :address1, :city, :county, :country, :reserved_seating, :sponsored, :with => /[a-z]+/i, :presence => true
  validates_format_of :organizer_email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, :presence => true
  validates_format_of :organizer_contact_no, :with => /[0-9]+/i, :presence => true
  validates :start_time, :end_time, :publish_time, :presence => true

  validates_length_of :title, :venue, :address1, minimum: 5, allow_blank: false
  validates_length_of :description, minimum: 20, allow_blank: false

  validate :validate_date

  private

  def validate_date
    return if end_time.blank? || start_time.blank? || publish_time.blank?

    if start_time.strftime("%Y-%m-%d %H:%M:%S") < Time.now.strftime("%Y-%m-%d %H:%M:%S")
      errors.add(:start_time, "should be greater than current time")
    end

    if end_time.strftime("%Y-%m-%d %H:%M:%S") < Time.now.strftime("%Y-%m-%d %H:%M:%S")
      errors.add(:end_time, "should be greater than current time")
    end

    if end_time < start_time
      errors.add(:end_time, "cannot be less than start time")
    end

    if publish_time > start_time
      errors.add(:start_time, "cannot be less than publish time")
    end
  end
end

app/controllers/events_controller.rb
require 'log'
require_relative '../../app/pdfs/events_pdf'

$upcoming_events = Event.new
$user_orders_events = Order.new

class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :set_recommendation_vars, only: [:index, :show]
  include Pagy::Backend

  # GET /events
  # GET /events.json
  def index
    if user_signed_in?
      unless $upcoming_events.nil?
        ##### Based on your interests - START #####
        user_interests = User.select(:interest1, :interest2, :interest3, :interest4, :interest5).where(id: current_user.id)

        unless user_interests.nil?
          Log.debug("user_interests => " + user_interests.inspect)
          puts "user_interests => " + user_interests.inspect

          unless $user_orders_events.nil?
            @user_interests_events = Event.where(id: $upcoming_events).where("category in (?, ?, ?, ?, ?)",
                                                                          user_interests.as_json[0]["interest1"],
                                                                          user_interests.as_json[0]["interest2"],
                                                                          user_interests.as_json[0]["interest3"],
                                                                          user_interests.as_json[0]["interest4"],
                                                                          user_interests.as_json[0]["interest5"])
                                       .where.not(id: $user_orders_events).order("start_time ASC").first(5)
          else
            @user_interests_events = Event.where(id: $upcoming_events).where("category in (?, ?, ?, ?, ?)",
                                                                            user_interests.as_json[0]["interest1"],
                                                                            user_interests.as_json[0]["interest2"],
                                                                            user_interests.as_json[0]["interest3"],
                                                                            user_interests.as_json[0]["interest4"],
                                                                            user_interests.as_json[0]["interest5"])
                                         .order("start_time ASC").first(5)
          end

          unless @user_interests_events.nil?
            Log.debug("user_interests_events => " + @user_interests_events.inspect)
            puts "user_interests_events => " + @user_interests_events.inspect
          else
            Log.debug("user_interests_events => NULL")
            puts "user_interests_events => NULL"
          end
        else
          Log.debug("user_interests => NULL")
          puts "user_interests => NULL"
        end
        ##### Based on your interests - END #####

        ##### Previously viewed - START #####
        @previously_viewed_user_events = Event.where("events.id in (select event_id from viewed_events where user_id = #{current_user.id} order by view_time desc)").first(5)

        unless @previously_viewed_user_events.nil?
          Log.debug("previously_viewed_user_events => " + @previously_viewed_user_events.inspect)
          puts "previously_viewed_user_events => " + @previously_viewed_user_events.inspect
        else
          Log.debug("previously_viewed_user_events => NULL")
          puts "previously_viewed_user_events => NULL"
        end
        ##### Previously viewed - END #####
      end
    end

    @pagy, @events = pagy($upcoming_events, page: params[:page], items: 10)

    respond_to do |format|
      format.xlsx {
        response.headers[
            'Content-Disposition'
        ] = "attachment; filename=events.xlsx"
      }

      format.html { render :index }

      format.pdf do
        pdf = EventsPdf.new($upcoming_events)

        #pdf.encrypt_document(
        #    user_password: 'Event@12345',
        #    owner_password: 'Event@12345',
        #    permissions: {
        #        print_document: false,
        #        modify_contents: false,
        #        copy_contents: false,
        #        modify_annotations: false
        #    }
        #)

        send_data pdf.render,
                  filename: 'events.pdf',
                  type: 'application/pdf',
                  page_size: 'A4',
                  template: "events/index.html.erb",
                  layout: "pdf.html",
                  orientation: "Landscape",
                  lowquality: true,
                  zoom: 1,
                  dpi: 75
      end
    end
  end

  def showOrganizerEvents
    @usernames = params[:user_id].split(' ')
    @userid = User.where("first_name=? AND last_name=?",@usernames[0],@usernames[1]).first
    @events = Event.where("user_id=?",@userid)
  end

  # GET /events/1
  # GET /events/1.json
  def show
    if user_signed_in?
      unless $upcoming_events.nil?
        user_ids = ""
        event_ids = ""
        events_count = Hash.new(0)
        events_sorted = Hash.new(0)
        events_sorted_array = Array.new
                
        organizer_id = Event.find(params[:id]).user_id
        subscribe_check_query = ActiveRecord::Base.connection.execute("select * from subscriptions where subscribed_user_id = '#{organizer_id}' and user_id = #{current_user.id} ")
        wishlist_check_query = ActiveRecord::Base.connection.execute("select * from wishlists where event_id = #{params[:id]} and user_id = #{current_user.id} ")
        
        if(subscribe_check_query.as_json != [])
          @isSubscribed = true
        else
          @isSubscribed = false
        end

        if(wishlist_check_query.as_json != [])
          @isWishlisted = true
        else
          @isWishlisted = false
        end
        
        @isSubscribed
        @isWishlisted
        
        upsert_viewed_events

        ##### Customers who bought this also bought - START #####
        other_users_common_orders = Order.distinct.select(:user_id).where(event_id: $upcoming_events, event_id: $user_orders_events)
                                        .where.not(user_id: current_user.id)

        unless other_users_common_orders.nil?
          Log.debug("other_users_common_orders => " + other_users_common_orders.inspect)
          puts "other_users_common_orders => " + other_users_common_orders.inspect

          other_users_uncommon_orders_events = Order.distinct.select(:event_id).where(event_id: $upcoming_events, user_id: other_users_common_orders)
                                                   .where.not(event_id: $user_orders_events, event_id: params[:id])

          unless other_users_uncommon_orders_events.nil?
            Log.debug("other_users_uncommon_orders_events => " + other_users_uncommon_orders_events.inspect)
            puts "other_users_uncommon_orders_events => " + other_users_uncommon_orders_events.inspect

            @other_users_events = Event.where(id: other_users_uncommon_orders_events).order("start_time ASC").first(5)

            unless @other_users_events.nil?
              Log.debug("other_users_events => " + @other_users_events.inspect)
              puts "other_users_events => " + @other_users_events.inspect
            else
              Log.debug("other_users_events => NULL")
              puts "other_users_events => NULL"
            end
          else
            Log.debug("other_users_uncommon_orders_events => NULL")
            puts "other_users_uncommon_orders_events => NULL"
          end
        else
          Log.debug("other_users_common_orders => NULL")
          puts "other_users_common_orders => NULL"
        end
        ##### Customers who bought this also bought - END #####

        ##### Customers who viewed this also viewed - START #####
        select_query = "select distinct user_id from viewed_events where event_id = #{params[:id]} and user_id != #{current_user.id}"
        other_users = ActiveRecord::Base.connection.execute(select_query)

        unless other_users.nil?
          Log.debug("other_users => " + other_users.as_json.to_s)
          puts "other_users => " + other_users.as_json.to_s

          other_users.each do |user|
            if user_ids != ""
              user_ids += ", "
            end

            user_ids += user["user_id"].to_s
          end

          if user_ids != ""
            Log.debug("user_ids =>" + user_ids)
            puts "user_ids =>" + user_ids

            select_query_1 = "select distinct event_id from viewed_events where user_id in (" + user_ids + ") "
            select_query_1 += "and event_id not in (select distinct event_id from viewed_events where user_id = #{current_user.id} and event_id = #{params[:id]})"
            other_events = ActiveRecord::Base.connection.execute(select_query_1)

            unless other_events.nil?
              Log.debug("other_events => " + other_events.as_json.to_s)
              puts "other_events => " + other_events.as_json.to_s

              other_events.each do |event|
                if event_ids != ""
                  event_ids += ", "
                end

                event_ids += event["event_id"].to_s
              end

              if event_ids != ""
                Log.debug("event_ids => " + event_ids)
                puts "event_ids => " + event_ids

                upcoming_events_1 = Event.where(id: $upcoming_events).where("id in (" + event_ids + ")").order("start_time ASC")

                unless upcoming_events_1.nil?
                  Log.debug("upcoming_events_1 => " + upcoming_events_1.inspect)
                  puts "upcoming_events_1 => " + upcoming_events_1.inspect

                  upcoming_events_1.each do |event|
                    count = 0
                    Log.debug("event.id => " + event.id.to_s)
                    puts "event.id => " + event.id.to_s

app/helpers/events_helper.rb
module EventsHelper
  include Pagy::Frontend
end

app/views/events/edit.html.erb
<%= render 'form', event: @event %>

app/views/events/index.html.erb
<br>
<% if user_signed_in? %>
  <div class="btn btn-outline-primary">
    <%= link_to 'New Event', new_event_path, :class => "btn" %>
  </div>
  <div class="btn btn-outline-primary">
    <%= link_to 'Upload Events', events_imports_new_path, :class => "btn" %>
  </div>
  <div class="btn btn-outline-primary">
    <%= link_to 'Download Event List - Excel', events_path(format: :xlsx), :class => "btn" %>
  </div>
  <div class="btn btn-outline-primary">
    <%= link_to 'Download Event List - PDF', events_path(format: :pdf), :class => "btn" %>
  </div>
<% end %>

<% if @events == nil %>
  <h3> No events to display. </h3>
<% else %>
  <table class="table table-bordered">
    <% @events.each do |event| %>
      <table class="table table-bordered">
        <tr>
          <td width="30%">
            <%= image_tag event.picture_url, width: "75%", class: "rounded float-left" if event.picture.present? %>
          </td>
          <td>
            <table class="table table-hover">
              <tr>
                <h4><%= link_to event.title, event, class: "badge badge-light" %></h4>
              </tr>
              <thead>
                <tr>
                  <th scope="col">Category</th>
                  <th scope="col">Description</th>
                  <th scope="col">Venue</th>
                  <th scope="col">Start Time</th>
                  <th scope="col">End Time</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>
                    <%= event.category %>
                  </td>
                  <td>
                    <%= event.description %>
                  </td>
                  <td>
                    <%= event.venue %>
                  </td>
                  <td>
                    <%= event.start_time.strftime("%d/%m/%Y %I:%M%p") %>
                  </td>
                  <td>
                    <%= event.end_time.strftime("%d/%m/%Y %I:%M%p") %>
                  </td>
                </tr>
              </tbody>
            </table>
          </td>
        </tr>
      </table>
    <% end %>
  </table>
<% end %>
<%= pagy_bootstrap_nav(@pagy).html_safe %>

<br>
<br>

<% if user_signed_in? %>
  <% if @user_interests_events == nil %>
    <h3> No events to display based on your interests. </h3>
  <% else %>
    <h3> Based on your interests: </h3>
    <table class="table table-bordered">
      <% @user_interests_events.each do |user_interests_event| %>
        <table class="table table-bordered">
          <tr>
            <td width="30%">
              <%= image_tag user_interests_event.picture_url, width: "75%", class: "rounded float-left" if user_interests_event.picture.present? %>
            </td>
            <td>
              <table class="table table-hover">
                <tr>
                  <h4><%= link_to user_interests_event.title, user_interests_event, class: "badge badge-light" %></h4>
                </tr>
                <thead>
                <tr>
                  <th scope="col">Category</th>
                  <th scope="col">Description</th>
                  <th scope="col">Venue</th>
                  <th scope="col">Start Time</th>
                  <th scope="col">End Time</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                  <td>
                    <%= user_interests_event.category %>
                  </td>
                  <td>
                    <%= user_interests_event.description %>
                  </td>
                  <td>
                    <%= user_interests_event.venue %>
                  </td>
                  <td>
                    <%= user_interests_event.start_time.strftime("%d/%m/%Y %I:%M%p") %>
                  </td>
                  <td>
                    <%= user_interests_event.end_time.strftime("%d/%m/%Y %I:%M%p") %>
                  </td>
                </tr>
                </tbody>
              </table>
            </td>
          </tr>
        </table>
      <% end %>
    </table>
  <% end %>

  <br>
  <br>

  <% if @previously_viewed_user_events == nil %>
    <h3> No events to display based on your previous views. </h3>
  <% else %>
    <h3> Previously viewed events: </h3>
    <table class="table table-bordered">
      <% @previously_viewed_user_events.each do |previously_viewed_event| %>
        <table class="table table-bordered">
          <tr>
            <td width="30%">
              <%= image_tag previously_viewed_event.picture_url, width: "75%", class: "rounded float-left" if previously_viewed_event.picture.present? %>
            </td>
            <td>
              <table class="table table-hover">
                <tr>
                  <h4><%= link_to previously_viewed_event.title, previously_viewed_event, class: "badge badge-light" %></h4>
                </tr>
                <thead>
                <tr>
                  <th scope="col">Category</th>
                  <th scope="col">Description</th>
                  <th scope="col">Venue</th>
                  <th scope="col">Start Time</th>
                  <th scope="col">End Time</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                  <td>
                    <%= previously_viewed_event.category %>
                  </td>
                  <td>
                    <%= previously_viewed_event.description %>
                  </td>
                  <td>
                    <%= previously_viewed_event.venue %>
                  </td>
                  <td>
                    <%= previously_viewed_event.start_time.strftime("%d/%m/%Y %I:%M%p") %>
                  </td>
                  <td>
                    <%= previously_viewed_event.end_time.strftime("%d/%m/%Y %I:%M%p") %>
                  </td>
                </tr>
                </tbody>
              </table>
            </td>
          </tr>
        </table>
      <% end %>
    </table>
  <% end %>
<% end %>
<br>

app/views/events/new.html.erb
<%= render 'form', event: @event %>

app/views/events/show.html.erb
<table class="table table-striped">
  <tbody>
    <tr>
      <%= image_tag (@event.picture_url.to_s), width: '30%', class: "img-thumbnail" if @event.picture.present? %>
    </tr>
    <tr>
      <td>
      <p>
        <strong>Title:</strong>
        <%= @event.title %>
      </p>
      </td>
      <td>
      <p>
        <strong>Category:</strong>
        <%= @event.category %>
      </p>
      </td>
      <td>
      <p>
        <strong>Description:</strong>
        <%= @event.description %>
      </p>
      </td>
      <td>
      <p>
        <strong>Organizer name:</strong>
        <%= @event.organizer_name %>
      </p>
      </td>
      <td>
      <p>
        <strong>Organizer email:</strong>
        <%= @event.organizer_email %>
      </p>
      </td>
    </tr>
    <tr>
      <td>
      <p>
        <strong>Organizer contact no:</strong>
        <%= @event.organizer_contact_no.to_i %>
      </p>
      </td>
      <td>
      <p>
        <strong>Venue:</strong>
        <%= @event.venue %>
      </p>
      </td>
      <td>
      <p>
        <strong>Address1:</strong>
        <%= @event.address1 %>
      </p>
      </td>
      <td>
      <p>
        <strong>Address2:</strong>
        <%= @event.address2 %>
      </p>
      </td>
      <td>
      <p>
        <strong>City:</strong>
        <%= @event.city %>
      </p>
      </td>
    </tr>
    <tr>
      <td>
      <p>
        <strong>County:</strong>
        <%= @event.county %>
      </p>
      </td>
      <td>
      <p>
        <strong>Country:</strong>
        <%= @event.country %>
      </p>
      </td>
      <td>
      <p>
        <strong>Start time:</strong>
        <%= @event.start_time.strftime("%d/%m/%Y %I:%M%p") %>
      </p>
      </td>
      <td>
      <p>
        <strong>End time:</strong>
        <%= @event.end_time.strftime("%d/%m/%Y %I:%M%p") %>
      </p>
      </td>
      <td>
      <p>
        <strong>Publish time:</strong>
        <%= @event.publish_time.strftime("%d/%m/%Y %I:%M%p") %>
      </p>
      </td>
    </tr>
    <tr>
      <td>
      <p>
        <strong>Reserved seating:</strong>
        <%= @event.reserved_seating %>
      </p>
      </td>
      <td>
      <p>
        <strong>Sponsored:</strong>
        <%= @event.sponsored %>
      </p>
      </td>
      <td>
        <p>
          <strong>Overall Rating:</strong>
          <% unless @event.overall_rating.nil? || @event.overall_rating == 0.0 %>
            <%= link_to @event.overall_rating, {:controller => "ratings", :action => "showEventRating", :events_id => @event.id }  %>
          <% else %>
            --
          <% end %>
        </p>
      </td>
      <td/>
      <td/>
    </tr>
    <tr>
      <td/>
      <td>
        <%= link_to 'Tickets', event_tickets_path(@event), :class => "btn btn-outline-primary" %>
      </td>
      <td>
        <%= link_to 'Back', events_path, :class => "btn btn-outline-primary" %>
      </td>
      <% if user_signed_in? && @event.user_id == current_user.id %>
        <td>
          <%= link_to 'Edit', edit_event_path, :class => "btn btn-outline-primary" %>
        </td>
        <td>
          <%= link_to 'Delete', event_path, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-outline-primary" %>
        </td>
        <% else %>
        <% if user_signed_in? %>
          <% if !@isSubscribed %>
            <td>
            <% @subscription = Hash.new %>
            <% @subscription["subscribed_user_id"] = @event.user_id %>
            <% @subscription["subscription_date"] = Time.now %>
            <% @subscription["user_id"] = current_user.id %>
            <%= link_to 'Subscribe to Organizer', {:controller => "subscriptions", :action => "create", :subscription => @subscription } , :method => :post, :class => "btn btn-outline-primary" %>
            </td>
          <% else %>
          <% @subscription = Hash.new %>
          <% @subscription["subscribed_user_id"] = @event.user_id %>
          <% @subscription["subscription_date"] = Time.now %>
          <% @subscription["user_id"] = current_user.id %>   
           <td><%= link_to 'Unsubscribe from Organizer',{:controller => "subscriptions", :action => "deleteSubscribeFromEvent", :subscription => @subscription }, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-outline-primary"  %></td>
          <% end %> 
          <% if !@isWishlisted %>
            <td>
            <% @wishlist = Hash.new %>
            <% @wishlist["wishlist_date"] = Time.now %>
            <% @wishlist["user_id"] = current_user.id %>
            <% @wishlist["event_id"] = @event.id %>
            <% @wishlist["event_name"] = @event.title %>
            <%= link_to 'Add to Wishlist', {:controller => "wishlists", :action => "create", :wishlist => @wishlist } , :method => :post, :class => "btn btn-outline-primary" %>
            </td>
          <% else %>
          <% @wishlist = Hash.new %>
            <% @wishlist["wishlist_date"] = Time.now %>
            <% @wishlist["user_id"] = current_user.id %>
            <% @wishlist["event_id"] = @event.id %>
            <% @wishlist["event_name"] = @event.title %>
            <td><%= link_to 'Remove from Wishlist',{:controller => "wishlists", :action => "deleteWishlistFromEvent", :wishlist => @wishlist }, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-outline-primary"  %></td>
          <% end %>
        <% end %>
      <% end %>
    </tr>
  </tbody>
</table>

<br>
<br>

<% if user_signed_in? %>
  <% if @other_users_events == nil %>
    <h3> No events to display based on your orders history. </h3>
  <% else %>
    <h3> Customers who bought this also bought: </h3>
    <table class="table table-bordered">
      <% @other_users_events.each do |other_users_event| %>
        <table class="table table-bordered">
          <tr>
            <td width="30%">
              <%= image_tag other_users_event.picture_url, width: "75%", class: "rounded float-left" if other_users_event.picture.present? %>
            </td>
            <td>
              <table class="table table-hover">
                <tr>
                  <h4><%= link_to other_users_event.title, other_users_event, class: "badge badge-light" %></h4>
                </tr>
                <thead>
                <tr>
                  <th scope="col">Category</th>
                  <th scope="col">Description</th>
                  <th scope="col">Venue</th>
                  <th scope="col">Start Time</th>
                  <th scope="col">End Time</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                  <td>
                    <%= other_users_event.category %>
                  </td>
                  <td>
                    <%= other_users_event.description %>
                  </td>
                  <td>
                    <%= other_users_event.venue %>
                  </td>
                  <td>
                    <%= other_users_event.start_time.strftime("%d/%m/%Y %I:%M%p") %>
                  </td>
                  <td>
                    <%= other_users_event.end_time.strftime("%d/%m/%Y %I:%M%p") %>
                  </td>
                </tr>
                </tbody>
              </table>
            </td>
          </tr>
        </table>
      <% end %>
    </table>
  <% end %>

  <br>
  <br>

  <% if @other_users_previously_viewed_events == nil %>
    <h3> No events to display based on other customer views. </h3>
  <% else %>
    <h3> Customers who viewed this also viewed: </h3>
    <table class="table table-bordered">
      <% @other_users_previously_viewed_events.each do |other_users_viewed_events| %>
        <table class="table table-bordered">
          <tr>
            <td width="30%">
              <%= image_tag other_users_viewed_events.picture_url, width: "75%", class: "rounded float-left" if other_users_viewed_events.picture.present? %>
            </td>
            <td>
              <table class="table table-hover">
                <tr>
                  <h4><%= link_to other_users_viewed_events.title, other_users_viewed_events, class: "badge badge-light" %></h4>
                </tr>
                <thead>
                <tr>
                  <th scope="col">Category</th>
                  <th scope="col">Description</th>
                  <th scope="col">Venue</th>
                  <th scope="col">Start Time</th>
                  <th scope="col">End Time</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                  <td>
                    <%= other_users_viewed_events.category %>
                  </td>
                  <td>
                    <%= other_users_viewed_events.description %>
                  </td>
                  <td>
                    <%= other_users_viewed_events.venue %>
                  </td>
                  <td>
                    <%= other_users_viewed_events.start_time.strftime("%d/%m/%Y %I:%M%p") %>
                  </td>
                  <td>
                    <%= other_users_viewed_events.end_time.strftime("%d/%m/%Y %I:%M%p") %>
                  </td>
                </tr>
                </tbody>
              </table>
            </td>
          </tr>
        </table>
      <% end %>
    </table>
  <% end %>
<% end %>
<br>

app/views/events/showOrganizerEvents.html.erb
<% if @events == nil %>
    <h3> No events to display. </h3>
  <% else %>
    <table class="table table-bordered">
      <% @events.each do |event| %>
        <table class="table table-bordered">
          <tr>
            <td width="30%">
              <%= image_tag event.picture_url, width: "75%", class: "rounded float-left" if event.picture.present? %>
            </td>
            <td>
              <table class="table table-hover">
                <tr>
                  <h4><%= link_to event.title, event, class: "badge badge-light" %></h4>
                </tr>
                <thead>
                  <tr>
                    <th scope="col">Category</th>
                    <th scope="col">Description</th>
                    <th scope="col">Venue</th>
                    <th scope="col">Start Time</th>
                    <th scope="col">End Time</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>
                      <%= event.category %>
                    </td>
                    <td>
                      <%= event.description %>
                    </td>
                    <td>
                      <%= event.venue %>
                    </td>
                    <td>
                      <%= event.start_time.strftime("%d/%m/%Y %I:%M%p") %>
                    </td>
                    <td>
                      <%= event.end_time.strftime("%d/%m/%Y %I:%M%p") %>
                    </td>
                  </tr>
                </tbody>
              </table>
            </td>
          </tr>
        </table>
      <% end %>
    </table>
  <% end %>

  