config/routes.rb
Rails.application.routes.draw do

  resources :notifications
  patch '/markAsRead' => 'notifications#markAsRead'
  get '/markAsRead' => 'notifications#index'
  
  get '/signedinuserprofile' => 'users#signedinuserprofile'
  
  post '/showOrganizerEvents' => 'events#showOrganizerEvents'
  get '/showOrganizerEvents' => 'events#showOrganizerEvents'
  
  post '/showEventRating' => 'ratings#showEventRating'
  get '/showEventRating' => 'ratings#showEventRating'

  delete '/deleteWishlistFromEvent' => 'wishlists#deleteWishlistFromEvent'

  delete '/deleteSubscribeFromEvent' => 'subscriptions#deleteSubscribeFromEvent'

  get 'events_imports/new'
  get 'events_imports/create'
  
  devise_for :users
  
  root 'home#index'
  
  get 'search/index' => 'search#index'
  post '/show' => 'search#show'
  
  get 'search/show' => 'search#show'
  get '/home/index' => 'home#index'

  resources :users
  resources :orders
  resources :wishlists
  resources :subscriptions

  resources :events do
    resources :tickets
  end

  resources :ratings
  
  resources :events_imports, only: [:new, :create]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :event, optional: true

  validates_format_of :user_rating, :with => /[0-9]+/i, :presence => true
  validates_format_of :user_review, :with => /[a-z]+/i, :presence => true

  validates :user_review,:rating_date,:ticket_id, :presence => true
  validate :check_rating_date
  
    private
  
    def check_rating_date
      return if rating_date.blank?
  
      if rating_date.strftime("%Y-%m-%d") < Time.now.strftime("%Y-%m-%d")
        errors.add(:rating_date, "should be greater than current time")
      end
    end  

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:show, :edit, :update, :destroy]
  # GET /ratings
  # GET /ratings.json
  def index
    @user = User.find(current_user.id)
    @events = Event.where(id: Order.where("user_id=?",@user.id).distinct.pluck("event_id"))
    @ratings = Array.new
    @events.each do |event|
      puts event
      puts event.start_time
      puts Time.now
      if event.start_time <= Time.now
        puts "inside insertion"
        @rating = Rating.where("users_id=? AND events_id=?",@user.id,event.id)
        @ratings << @rating if !@rating.nil? 
      end #inner if ends
    end
    @ratings.as_json
    puts @ratings  
  end

  def showEventRating
    unless params[:events_id].nil?
      @ratings = Rating.where("events_id = ? and user_rating>0.0",params[:events_id])
    end

    unless params["format"].nil?
      @ratings = Rating.where("events_id = ? and user_rating>0.0",params["format"])
    end
    
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings
  # POST /ratings.json
  def create
    @user = User.find(current_user.id)
    @rating = Rating.new(rating_params)
    respond_to do |format|
      if @rating.save
        format.html { redirect_to rating_url(@rating), notice: 'Rating was successfully added.' }
        format.json { render :show, status: :created, location: @rating }
      else
        format.html { render :new }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ratings/1
  # PATCH/PUT /ratings/1.json
  def update
    @rating = Rating.find(params[:id])
    @event = Event.where(params[:events_id]).first
    @user = User.find(@event.user_id)
    #rating_params[:events_id] = Event.where("title=?",rating_params[:events_id]).first.id
    respond_to do |format|
      if @rating.update(rating_params)
        #SendCustomMail.new(@user.email, "Event #{@event.title} was rated.").process.deliver
        format.html { redirect_to rating_url(@rating), notice: 'Rating was successfully updated.' }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating.destroy
  end

  def findEventName
    @event = Event.find(params[:event_id]) 
    @event.title
  end

  private
    
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rating_params
      params.require(:rating).permit(:user_rating, :user_review, :rating_date, :users_id, :events_id, :ticket_id)
    end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.erb
<%= form_with(model: rating, local: true) do |form| %>
  <% if rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
        <% rating.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_rating %>
    <%= form.select :user_rating, options_for_select(["0.5","1.0","1.5","2.0","2.5","3.0","3.5","4.0","4.5","5.0"]) %>
  </div>

  <div class="field">
    <%= form.label :user_review %>
    <%= form.text_area :user_review, rows: "3" %>
  </div>

  <div class="field">
    <%= form.label :events_name %>
    <%= form.text_field :events_name, :readonly => true, value: Event.find(rating.events_id).title %>
  </div>
  <div class="field">
  <%= form.hidden_field :events_id, :readonly => true, value: rating.events_id %>
  </div>
  
  <div class="field">
    <%= form.hidden_field :rating_date %>
    <%= form.hidden_field :rating_date, :readonly => true, value: Time.now.strftime("%F") %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ratings/edit.html.erb
<h1>Editing Rating</h1>

<%= render 'form', rating: @rating %>

<%= link_to 'Show', rating_path(@rating) %> |
<%= link_to 'Back', ratings_path() %>

app/views/ratings/index.html.erb
<% if @ratings == nil %>
  <h3> This User has no ratings yet. </h3>
  <% else %>
    <table class="table table-bordered">
      <thead>
          <th scope="col">User rating</th>
          <th scope="col">User review</th>
          <th scope="col">Event</th>
          <th colspan="2"></th>
      </thead>

      <tbody>
        <% @ratings.each do |rating| %>
          <% rating.each do |specrating| %>  
            <tr>
              <% if specrating.user_rating > 0.0 %>
                <td><%= specrating.user_rating %></td>
              <% else %>
                <td> -- </td>
              <% end %>
              <td><%= specrating.user_review %></td>
              <td><%= Event.find(specrating.events_id).title %></td>
              <td><%= link_to 'Show', rating_path(specrating), :class => "btn btn-outline-primary" %></td>
              <td><%= link_to 'Edit', edit_rating_path(specrating), :class => "btn btn-outline-primary" %></td>
              
            </tr>
            <% end %>    
        <% end %>
      </tbody>
    </table>
  <% end %>
<br>

app/views/ratings/new.html.erb
<h1>New Rating</h1>

<%= render 'form', rating: @rating %>

<%= link_to 'Back', user_ratings_path(@user) %>

app/views/ratings/show.html.erb
<p>
  <strong>User rating:</strong>
  <%= @rating.user_rating %>
</p>

<p>
  <strong>User review:</strong>
  <%= @rating.user_review %>
</p>
<p>
  <strong>Event:</strong>
  <%= Event.find(@rating.events_id).title %>
</p>


<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/showEventRating.html.erb
<% if @ratings == nil %>
    <h3> This User has no ratings yet. </h3>
    <% else %>
    
      <table class="table table-bordered">
        <thead>
            <th scope="col">User rating</th>
            <th scope="col">User review</th>
            <th scope="col">Event</th>
        </thead>
  
        <tbody>
          <% @ratings.each do |rating| %>
            <tr>
              <td><%= rating.user_rating %></td>
              <td><%= rating.user_review %></td>
              <td><%= Event.find(rating.events_id).title %></td>
            
            </tr>
          <% end %>
           
        </tbody>
      </table>
   
  <br>
<% end %>
  
  
  