config/routes.rb
Rails.application.routes.draw do

  resources :notifications
  patch '/markAsRead' => 'notifications#markAsRead'
  get '/markAsRead' => 'notifications#index'
  
  get '/signedinuserprofile' => 'users#signedinuserprofile'
  
  post '/showOrganizerEvents' => 'events#showOrganizerEvents'
  get '/showOrganizerEvents' => 'events#showOrganizerEvents'
  
  post '/showEventRating' => 'ratings#showEventRating'
  get '/showEventRating' => 'ratings#showEventRating'

  delete '/deleteWishlistFromEvent' => 'wishlists#deleteWishlistFromEvent'

  delete '/deleteSubscribeFromEvent' => 'subscriptions#deleteSubscribeFromEvent'

  get 'events_imports/new'
  get 'events_imports/create'
  
  devise_for :users
  
  root 'home#index'
  
  get 'search/index' => 'search#index'
  post '/show' => 'search#show'
  
  get 'search/show' => 'search#show'
  get '/home/index' => 'home#index'

  resources :users
  resources :orders
  resources :wishlists
  resources :subscriptions

  resources :events do
    resources :tickets
  end

  resources :ratings
  
  resources :events_imports, only: [:new, :create]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user

    USER_NAMES = []
    #@users = User.find_by_sql("select users.first_name,users.last_name from users join events on users.id=events.user_id")
    #@users.each do |name|
        #USER_NAMES << name.first_name + ' ' + name.last_name

    #end     #end of each loop
    validates :subscription_date,:subscribed_user_id,:user_id, :presence => true
    validate :check_subscription_date
  
    private
  
    def check_subscription_date
      return if subscription_date.blank?
  
      if subscription_date.strftime("%Y-%m-%d") < Time.now.strftime("%Y-%m-%d")
        errors.add(:subscription_date, "should be greater than current day")
      end
    end
  
end   #end of Model

app/controllers/subscriptions_controller.rb
require 'log'

class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    if user_signed_in?
      ##### Based on your interests - START #####

      already_subscribed_organizers = ActiveRecord::Base.connection.execute("select CAST(subscribed_user_id as BIGINT) from subscriptions where user_id = #{current_user.id}")

      user_interests = User.select(:interest1, :interest2, :interest3, :interest4, :interest5).where(id: current_user.id)
      
      @organizers = Array.new

      already_subscribed_organizers.as_json.each do |user|
        @organizers << user["subscribed_user_id"]
      end
      unless user_interests.nil?
        Log.debug("user_interests => " + user_interests.inspect)
        if @organizers == []
          user_interest_events = Event.distinct.select(:user_id).where("category in (?, ?, ?, ?, ?)",
                                                            user_interests.as_json[0]["interest1"],
                                                            user_interests.as_json[0]["interest2"],
                                                            user_interests.as_json[0]["interest3"],
                                                            user_interests.as_json[0]["interest4"],
                                                            user_interests.as_json[0]["interest5"])
                                                            .where.not(user_id: current_user.id)
            
        else
          user_interest_events = Event.distinct.select(:user_id).where("category in (?, ?, ?, ?, ?)",
                                                            user_interests.as_json[0]["interest1"],
                                                            user_interests.as_json[0]["interest2"],
                                                            user_interests.as_json[0]["interest3"],
                                                            user_interests.as_json[0]["interest4"],
                                                            user_interests.as_json[0]["interest5"])
                                    .where.not(user_id: current_user.id).where.not("user_id in (?)",@organizers)
        end
        unless user_interest_events.as_json == []
          @user_interest_organizers = Array.new
          Log.debug("user_interest_events => " + user_interest_events.inspect)
          user_interest_events.as_json.each do |organizer|
            @user_interest_organizers << User.where(id: organizer["user_id"]).first
          end
          unless @user_interest_organizers.nil?
            Log.debug("user_interest_organizers => " + @user_interest_organizers.inspect)
          else
            Log.debug("user_interest_organizers => NULL")
          end
        else
          Log.debug("user_interest_events => NULL")
        end
      else
        Log.debug("user_interests => NULL")
      end
      ##### Based on your interests - END #####
      
    end

    @user = User.find(current_user.id)
    @subscriptions = @user.subscriptions

    @subscriptions.each do |subscribe|
      @name = User.find(subscribe[:subscribed_user_id])
      subscribe.subscribed_user_id = (@name.first_name + " " + @name.last_name)
    end
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
    @user = User.find(current_user.id)
    @subscription = @user.subscriptions.find(params[:id])
    @name = User.find(@subscription[:subscribed_user_id])
    @subscription.subscribed_user_id = (@name.first_name + " " + @name.last_name)

  end

  # GET /subscriptions/new
  def new
    @user = User.find(current_user.id)
    @subscription = @user.subscriptions.build()
  end

  # GET /subscriptions/1/edit
  def edit
    @user = User.find(current_user.id)
    @subscription = @user.subscriptions.find(params[:id])
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    #@user = User.find(current_user.id)
    @subscription = Subscription.new(subscription_params)
    #@usernames = params[:subscription][:subscribed_user_id].split(' ')
    #@userid = User.where("first_name=? AND last_name=?",@usernames[0],@usernames[1]).first
    #@subscription.subscribed_user_id = @userid[:id]
    @current_user = User.find(current_user.id)
    @organizer_name = User.find(@subscription.subscribed_user_id)
    respond_to do |format|
      if @subscription.save
        #SendCustomMail.new(@current_user.email, "Subscribed Successfully to #{@organizer_name.first_name} #{@organizer_name.last_name}").process.deliver
        format.html { redirect_to subscription_url( @subscription), notice: 'Subscription was successfully added.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    @user = User.find(current_user.id)
    @usernames = params[:subscription][:subscribed_user_id].split(' ')
    @userid = User.where("first_name=? AND last_name=?",@usernames[0],@usernames[1]).first
    params[:subscription][:subscribed_user_id] = @userid.id
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to subscription_url(@subscription), notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def deleteSubscribeFromEvent
    @subscribe = Subscription.where("user_id = #{params[:subscription][:user_id]} and subscribed_user_id = '#{params[:subscription][:subscribed_user_id]}'").first
    @subscribe.destroy
    redirect_to root_path
  end
  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @user = User.find(current_user.id)
    @subscription = @user.subscriptions.find(params[:id])
    @subscription.destroy
    redirect_to subscriptions_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      params.require(:subscription).permit(:subscribed_user_id, :subscription_date, :user_id)
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= form_with(model: [@subscription], local: true) do |form| %>
  <% if subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
        <% subscription.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= form.label :subscribed_user_id %>
  <%= form.select(:subscribed_user_id, Subscription::USER_NAMES) %>
</div>

  <div class="field">
    <%= form.label :subscription_date %>
    <%= form.date_select :subscription_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing Subscription</h1>

<%= render 'form', subscription: @subscription %>

<%= link_to 'Show', subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path() %>

app/views/subscriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subscriptions</h1>
<% if @subscriptions == nil %>
  <h3> This User has no Subscription yet. </h3>
  <% else %>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Subscribed user</th>
          <th>Subscription date</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @subscriptions.each do |subscription| %>
          <tr>
            <td><%= link_to subscription.subscribed_user_id, {:controller => "events", :action => "showOrganizerEvents", :user_id => subscription.subscribed_user_id } %></td>
            <td><%= subscription.subscription_date %></td>
            <td><%= link_to 'Destroy', subscription_path(subscription) , method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-outline-primary" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
<br>

<% if user_signed_in? %>
  <% if @user_interest_organizers == nil %>
    <h3> No organizers to display based on your interests. </h3>
  <% else %>
    <h3> Based on your interests: </h3>
    <table class="table table-bordered">
      <thead>
      <tr>
        <th scope="col">Organizer Name</th>
        <th scope="col">Email</th>
        <th scope="col">Contact No</th>
        <th/>
      </tr>
      </thead>
      <% @user_interest_organizers.each do |user_interests_organizer| %>
        <tbody>
        <tr>
          <td>
            <%= link_to user_interests_organizer.first_name + " " + user_interests_organizer.last_name,{:controller => "events", :action => "showOrganizerEvents", :user_id => user_interests_organizer.first_name + " " + user_interests_organizer.last_name }  %>
          </td>
          <td>
            <%= user_interests_organizer.email %>
          </td>
          <td>
            <%= user_interests_organizer.contact_no.to_i %>
          </td>
          <td>
            <% @subscription = Hash.new %>
            <% @subscription["subscribed_user_id"] = user_interests_organizer.id %>
            <% @subscription["subscription_date"] = Time.now %>
            <% @subscription["user_id"] = current_user.id %>

            <%= link_to 'Subscribe to Organizer', {:controller => "subscriptions", :action => "create", :subscription => @subscription } , :method => :post, :class => "btn btn-outline-primary" %>
          </td>
        </tr>
        </tbody>
      <% end %>
    </table>
  <% end %>
<% end %>
<br>

app/views/subscriptions/new.html.erb
<h1>New Subscription</h1>

<%= render 'form', subscription: @subscription %>

<%= link_to 'Back', subscriptions_path() %>

app/views/subscriptions/show.html.erb
<p>
  <strong>Subscribed user:</strong>
  <%= @subscription.subscribed_user_id %>
</p>

<p>
  <strong>Subscription date:</strong>
  <%= @subscription.subscription_date %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>