config/routes.rb
Rails.application.routes.draw do

  resources :notifications
  patch '/markAsRead' => 'notifications#markAsRead'
  get '/markAsRead' => 'notifications#index'
  
  get '/signedinuserprofile' => 'users#signedinuserprofile'
  
  post '/showOrganizerEvents' => 'events#showOrganizerEvents'
  get '/showOrganizerEvents' => 'events#showOrganizerEvents'
  
  post '/showEventRating' => 'ratings#showEventRating'
  get '/showEventRating' => 'ratings#showEventRating'

  delete '/deleteWishlistFromEvent' => 'wishlists#deleteWishlistFromEvent'

  delete '/deleteSubscribeFromEvent' => 'subscriptions#deleteSubscribeFromEvent'

  get 'events_imports/new'
  get 'events_imports/create'
  
  devise_for :users
  
  root 'home#index'
  
  get 'search/index' => 'search#index'
  post '/show' => 'search#show'
  
  get 'search/show' => 'search#show'
  get '/home/index' => 'home#index'

  resources :users
  resources :orders
  resources :wishlists
  resources :subscriptions

  resources :events do
    resources :tickets
  end

  resources :ratings
  
  resources :events_imports, only: [:new, :create]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :user
  
  
  EVENT_NAME = []
  @events = Event.distinct.pluck(:title)

  @events.each do |names|
    EVENT_NAME << names
  end

  validates :wishlist_date,:user_id,:event_id, :presence => true
    validate :check_wishlist_date
  
    private
  
    def check_wishlist_date
      return if wishlist_date.blank?
  
      if wishlist_date.strftime("%Y-%m-%d") < Time.now.strftime("%Y-%m-%d")
        errors.add(:wishlist_date, "should be greater than current time")
      end
    end

end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  before_action :set_wishlist, only: [:show, :edit, :update, :destroy]

  # GET /wishlists
  # GET /wishlists.json
  def index
    @user = User.find(current_user.id)
    
    @wishlists = @user.wishlists

  end

  # GET /wishlists/1
  # GET /wishlists/1.json
  def show
    @user = User.find(current_user.id)
    @wishlist = @user.wishlists.find(params[:id])

  end

  # GET /wishlists/new
  def new
    @user = User.where("id=?",current_user.id).first
    @wishlist = @user.wishlists.build()
  end

  # GET /wishlists/1/edit
  def edit
    @user = User.where("id=?",current_user.id).first
    @wishlist = @user.wishlists.find(params[:id])
  end

  # POST /wishlists
  # POST /wishlists.json
  def create
    @user = User.find(current_user.id)
    @wishlist = @user.wishlists.build(wishlist_params)
    @event = params[:wishlist][:event_name]
    @eventid = Event.where("title=?",@event).first
    @wishlist.event_id = @eventid[:id]
    respond_to do |format|
      if @wishlist.save
        format.html { redirect_to wishlist_url(@wishlist), notice: 'wishlist was successfully added.' }
        format.json { render :show, status: :created, location: @wishlist }
      else
        format.html { render :new }
        format.json { render json: @wishlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wishlists/1
  # PATCH/PUT /wishlists/1.json
  def update
    @user = User.find(current_user.id)
    @event = params[:wishlist][:event_name]
    @eventid = Event.where("title=?",@event).first
    params[:wishlist][:event_id] = @eventid.id
    respond_to do |format|
      if @wishlist.update(wishlist_params)
        format.html { redirect_to wishlist_url(@wishlist), notice: 'wishlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @wishlist }
      else
        format.html { render :edit }
        format.json { render json: @wishlist.errors, status: :unprocessable_entity }
      end
    end
  end

  def deleteWishlistFromEvent
    @wishlist = Wishlist.where("user_id = '#{params[:wishlist][:user_id]}' and event_id = #{params[:wishlist][:event_id]}").first
    @wishlist.destroy
    redirect_to root_path
  end
  # DELETE /wishlists/1
  # DELETE /wishlists/1.json
  def destroy
    @user = User.find(current_user.id)
    @wishlist = @user.wishlists.find(params[:id])
    @wishlist.destroy
    redirect_to wishlists_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wishlist
      @wishlist = Wishlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wishlist_params
      params.require(:wishlist).permit(:wishlist_date, :event_name, :event_id )
    end
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/wishlists/_form.html.erb
<%= form_with(model: [@wishlist], local: true) do |form| %>
  <% if wishlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wishlist.errors.count, "error") %> prohibited this wishlist from being saved:</h2>

      <ul>
        <% wishlist.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :wishlist_date %>
    <%= form.date_select :wishlist_date %>
  </div>

  <div class="field">
  <%= form.label :event_id %>
  <%= form.select(:event_name, Wishlist::EVENT_NAME) %>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wishlists/edit.html.erb
<h1>Editing Wishlist</h1>

<%= render 'form', wishlist: @wishlist %>

<%= link_to 'Show', wishlist_path(@wishlist) %> |
<%= link_to 'Back', wishlists_path() %>

app/views/wishlists/index.html.erb
<h1>Wishlists</h1>
<% if @wishlists == nil %>
  <h3> This User has no Wishlists yet. </h3>
  <% else %>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Event Name</th>
          <th>Wishlist date</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @wishlists.each do |wishlist| %>
          <tr>
            <td><%= link_to wishlist.event_name, event_path(wishlist.event_id) %></td>
            <td><%= wishlist.wishlist_date %></td>
            <td><%= link_to 'Destroy', wishlist_path(wishlist) , method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-outline-primary" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>        
<br>

app/views/wishlists/new.html.erb
<h1>New Wishlist</h1>

<%= render 'form', wishlist: @wishlist %>

<%= link_to 'Back', wishlists_path() %>

app/views/wishlists/show.html.erb
<p>
  <strong>Wishlist date:</strong>
  <%= @wishlist.wishlist_date %>
</p>

<p>
  <strong>Event Name:</strong>
  <%= @wishlist.event_name %>
</p>

<%= link_to 'Edit', edit_wishlist_path(@wishlist) %> |
<%= link_to 'Back', wishlists_path %>